version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'database'
    # app running on port 3000, direct to HTTPS (443) & to HTTP (80)
    ports:
      - '443:3000'
      - '80:3000'

  # create database image
  database:
    image: mongo:latest

  # webpack:
  #   build: .
  #   command: npm run build
  seed:
    build: .
    command: npm run seed
