const locations = ([
  { id: 'Alabama', color: 'grey', text: 'Alabama' },
  { id: 'Alaska', color: 'grey', text: 'Alaska' },
  { id: 'Arizona', color: 'grey', text: 'Arizona' },
  { id: 'Arkansas', color: 'grey', text: 'Arkansas' },
  { id: 'California', color: 'grey', text: 'California' },
  { id: 'Colorado', color: 'grey', text: 'Colorado' },
  { id: 'Connecticut', color: 'grey', text: 'Connecticut' },
  { id: 'Delaware', color: 'grey', text: 'Delaware' },
  { id: 'Florida', color: 'grey', text: 'Florida' },
  { id: 'Georgia', color: 'grey', text: 'Georgia' },
  { id: 'Hawaii', color: 'grey', text: 'Hawaii' },
  { id: 'Idaho', color: 'grey', text: 'Idaho' },
  { id: 'Illinois', color: 'grey', text: 'Illinois' },
  { id: 'Indiana', color: 'grey', text: 'Indiana' },
  { id: 'Iowa', color: 'grey', text: 'Iowa' },
  { id: 'Kansas', color: 'grey', text: 'Kansas' },
  { id: 'Kentucky', color: 'grey', text: 'Kentucky' },
  { id: 'Louisiana', color: 'grey', text: 'Louisiana' },
  { id: 'Maine', color: 'grey', text: 'Maine' },
  { id: 'Maryland', color: 'grey', text: 'Maryland' },
  { id: 'Massachusetts', color: 'grey', text: 'Massachusetts' },
  { id: 'Michigan', color: 'grey', text: 'Michigan' },
  { id: 'Minnesota', color: 'grey', text: 'Minnesota' },
  { id: 'Mississippi', color: 'grey', text: 'Mississippi' },
  { id: 'Missouri', color: 'grey', text: 'Missouri' },
  { id: 'Montana', color: 'grey', text: 'Montana' },
  { id: 'Nebraska', color: 'grey', text: 'Nebraska' },
  { id: 'Nevada', color: 'grey', text: 'Nevada' },
  { id: 'New Hampshire', color: 'grey', text: 'New Hampshire' },
  { id: 'New Jersey', color: 'grey', text: 'New Jersey' },
  { id: 'New Mexico', color: 'grey', text: 'New Mexico' },
  { id: 'New York', color: 'grey', text: 'New York' },
  { id: 'North Carolina', color: 'grey', text: 'North Carolina' },
  { id: 'North Dakota', color: 'grey', text: 'North Dakota' },
  { id: 'Ohio', color: 'grey', text: 'Ohio' },
  { id: 'Oklahoma', color: 'grey', text: 'Oklahoma' },
  { id: 'Oregon', color: 'grey', text: 'Oregon' },
  { id: 'Pennsylvania', color: 'grey', text: 'Pennsylvania' },
  { id: 'Rhode Island', color: 'grey', text: 'Rhode Island' },
  { id: 'South Carolina', color: 'grey', text: 'South Carolina' },
  { id: 'South Dakota', color: 'grey', text: 'South Dakota' },
  { id: 'Tennessee', color: 'grey', text: 'Tennessee' },
  { id: 'Texas', color: 'grey', text: 'Texas' },
  { id: 'Utah', color: 'grey', text: 'Utah' },
  { id: 'Vermont', color: 'grey', text: 'Vermont' },
  { id: 'Virginia', color: 'grey', text: 'Virginia' },
  { id: 'Washington', color: 'grey', text: 'Washington' },
  { id: 'West Virginia', color: 'grey', text: 'West Virginia' },
  { id: 'Wisconsin', color: 'grey', text: 'Wisconsin' },
  { id: 'Wyoming', color: 'grey', text: 'Wyoming' },
]);

export default locations;
